version: '3.8'

services:
  remix:
    build: .
    container_name: remix-app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"

  nginx:
    image: nginx:stable
    container_name: remix-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - remix
